/*
    SIR CODE
      
let obj = {
  name: "urvish",
  age: 123,
  hobby: ["reading", "playing"],
};

// to convert normal data into json string
let jsonData = JSON.stringify(obj);
console.log("🚀 ~ file: JSON.js:9 ~ jsonData:", jsonData);

// to convert json string into normal data
let normalData = JSON.parse(jsonData);
console.log("🚀 ~ file: JSON.js:12 ~ normalData:", normalData);

 -------------------------------------------------------------------
 -------------------------------------------------------------------
         MY CODE

let object = {
  name: "Tejas",
  age: 25,
  hobby: ["Reading", "Travelling", "Playing"],
};

// To convert normal data into JSON string

let Jsondata = JSON.stringify(object);

console.log("🚀 ~ file: 16_JSON.JS:27 ~ Jsondata:", Jsondata)

//To convert Json string into normal data;

let normalData = JSON.parse(Jsondata);

console.log("🚀 ~ file: 16_JSON.JS:32 ~ normalData:", normalData)

*/
